package rules.person;

import com.github.sbb.drools.entity.Person;
import com.github.sbb.drools.entity.School;

rule "person"
    when
    then
      System.out.println("person\t");
end

rule "person2"
    when
      $p:Person()
    then
      $p.setAge(20);
      System.out.println("person age 20\t" + $p);
end

rule "person_age30"
    when
      $p:Person(age==30)
    then
      $p.setAge(40);
      update($p)
      System.out.println("person age 30 \t" + $p);
end

rule "person_age40"
    when
      $p:Person(age==40)
    then
      System.out.println("person age 40 \t" + $p);
end

rule "person_ageMod10"
    when
      $p:Person(age % 10 ==0)
    then
      System.out.println("person age mod 10\t" + $p);
end

rule "person_contains"
    when
      $s:School()
      $p:Person(className contains $s.className)
    then
      System.out.println("person_contains\t" + $p);
end

rule "person_memberof"
    when
      $s:School()
      $p:Person(className memberOf $s.className)
    then
      System.out.println("person_memberOf\t" + $p);
end